// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: api/convoy.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ShellOutput_Stream int32

const (
	ShellOutput_STREAM_UNSPECIFIED ShellOutput_Stream = 0
	ShellOutput_STDOUT             ShellOutput_Stream = 1
	ShellOutput_STDERR             ShellOutput_Stream = 2
)

// Enum value maps for ShellOutput_Stream.
var (
	ShellOutput_Stream_name = map[int32]string{
		0: "STREAM_UNSPECIFIED",
		1: "STDOUT",
		2: "STDERR",
	}
	ShellOutput_Stream_value = map[string]int32{
		"STREAM_UNSPECIFIED": 0,
		"STDOUT":             1,
		"STDERR":             2,
	}
)

func (x ShellOutput_Stream) Enum() *ShellOutput_Stream {
	p := new(ShellOutput_Stream)
	*p = x
	return p
}

func (x ShellOutput_Stream) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ShellOutput_Stream) Descriptor() protoreflect.EnumDescriptor {
	return file_api_convoy_proto_enumTypes[0].Descriptor()
}

func (ShellOutput_Stream) Type() protoreflect.EnumType {
	return &file_api_convoy_proto_enumTypes[0]
}

func (x ShellOutput_Stream) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ShellOutput_Stream.Descriptor instead.
func (ShellOutput_Stream) EnumDescriptor() ([]byte, []int) {
	return file_api_convoy_proto_rawDescGZIP(), []int{6, 0}
}

type HealthResponse_Status int32

const (
	HealthResponse_STATUS_UNKNOWN   HealthResponse_Status = 0
	HealthResponse_STATUS_HEALTHY   HealthResponse_Status = 1
	HealthResponse_STATUS_DEGRADED  HealthResponse_Status = 2
	HealthResponse_STATUS_UNHEALTHY HealthResponse_Status = 3
)

// Enum value maps for HealthResponse_Status.
var (
	HealthResponse_Status_name = map[int32]string{
		0: "STATUS_UNKNOWN",
		1: "STATUS_HEALTHY",
		2: "STATUS_DEGRADED",
		3: "STATUS_UNHEALTHY",
	}
	HealthResponse_Status_value = map[string]int32{
		"STATUS_UNKNOWN":   0,
		"STATUS_HEALTHY":   1,
		"STATUS_DEGRADED":  2,
		"STATUS_UNHEALTHY": 3,
	}
)

func (x HealthResponse_Status) Enum() *HealthResponse_Status {
	p := new(HealthResponse_Status)
	*p = x
	return p
}

func (x HealthResponse_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HealthResponse_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_api_convoy_proto_enumTypes[1].Descriptor()
}

func (HealthResponse_Status) Type() protoreflect.EnumType {
	return &file_api_convoy_proto_enumTypes[1]
}

func (x HealthResponse_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HealthResponse_Status.Descriptor instead.
func (HealthResponse_Status) EnumDescriptor() ([]byte, []int) {
	return file_api_convoy_proto_rawDescGZIP(), []int{9, 0}
}

type CopyStart_Direction int32

const (
	CopyStart_DIRECTION_UNSPECIFIED CopyStart_Direction = 0
	CopyStart_TO_AGENT              CopyStart_Direction = 1 // Client sends tar data to agent (push)
	CopyStart_FROM_AGENT            CopyStart_Direction = 2 // Agent sends tar data to client (pull)
)

// Enum value maps for CopyStart_Direction.
var (
	CopyStart_Direction_name = map[int32]string{
		0: "DIRECTION_UNSPECIFIED",
		1: "TO_AGENT",
		2: "FROM_AGENT",
	}
	CopyStart_Direction_value = map[string]int32{
		"DIRECTION_UNSPECIFIED": 0,
		"TO_AGENT":              1,
		"FROM_AGENT":            2,
	}
)

func (x CopyStart_Direction) Enum() *CopyStart_Direction {
	p := new(CopyStart_Direction)
	*p = x
	return p
}

func (x CopyStart_Direction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CopyStart_Direction) Descriptor() protoreflect.EnumDescriptor {
	return file_api_convoy_proto_enumTypes[2].Descriptor()
}

func (CopyStart_Direction) Type() protoreflect.EnumType {
	return &file_api_convoy_proto_enumTypes[2]
}

func (x CopyStart_Direction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CopyStart_Direction.Descriptor instead.
func (CopyStart_Direction) EnumDescriptor() ([]byte, []int) {
	return file_api_convoy_proto_rawDescGZIP(), []int{11, 0}
}

// CommandRequest describes a non-interactive command to execute.
type CommandRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Args           []string               `protobuf:"bytes,1,rep,name=args,proto3" json:"args,omitempty"` // first element is program path
	Env            map[string]string      `protobuf:"bytes,2,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	WorkDir        string                 `protobuf:"bytes,3,opt,name=work_dir,json=workDir,proto3" json:"work_dir,omitempty"`
	TimeoutSeconds int32                  `protobuf:"varint,4,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CommandRequest) Reset() {
	*x = CommandRequest{}
	mi := &file_api_convoy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandRequest) ProtoMessage() {}

func (x *CommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_convoy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandRequest.ProtoReflect.Descriptor instead.
func (*CommandRequest) Descriptor() ([]byte, []int) {
	return file_api_convoy_proto_rawDescGZIP(), []int{0}
}

func (x *CommandRequest) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *CommandRequest) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *CommandRequest) GetWorkDir() string {
	if x != nil {
		return x.WorkDir
	}
	return ""
}

func (x *CommandRequest) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

// CommandResponse contains the execution result.
type CommandResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stdout        string                 `protobuf:"bytes,1,opt,name=stdout,proto3" json:"stdout,omitempty"`
	Stderr        string                 `protobuf:"bytes,2,opt,name=stderr,proto3" json:"stderr,omitempty"`
	ExitCode      int32                  `protobuf:"varint,3,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandResponse) Reset() {
	*x = CommandResponse{}
	mi := &file_api_convoy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandResponse) ProtoMessage() {}

func (x *CommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_convoy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandResponse.ProtoReflect.Descriptor instead.
func (*CommandResponse) Descriptor() ([]byte, []int) {
	return file_api_convoy_proto_rawDescGZIP(), []int{1}
}

func (x *CommandResponse) GetStdout() string {
	if x != nil {
		return x.Stdout
	}
	return ""
}

func (x *CommandResponse) GetStderr() string {
	if x != nil {
		return x.Stderr
	}
	return ""
}

func (x *CommandResponse) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *CommandResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// ShellRequest multiplexes shell session control over a bidi stream.
type ShellRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ShellRequest_Start
	//	*ShellRequest_Input
	Payload       isShellRequest_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShellRequest) Reset() {
	*x = ShellRequest{}
	mi := &file_api_convoy_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShellRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShellRequest) ProtoMessage() {}

func (x *ShellRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_convoy_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShellRequest.ProtoReflect.Descriptor instead.
func (*ShellRequest) Descriptor() ([]byte, []int) {
	return file_api_convoy_proto_rawDescGZIP(), []int{2}
}

func (x *ShellRequest) GetPayload() isShellRequest_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ShellRequest) GetStart() *ShellStart {
	if x != nil {
		if x, ok := x.Payload.(*ShellRequest_Start); ok {
			return x.Start
		}
	}
	return nil
}

func (x *ShellRequest) GetInput() *ShellInput {
	if x != nil {
		if x, ok := x.Payload.(*ShellRequest_Input); ok {
			return x.Input
		}
	}
	return nil
}

type isShellRequest_Payload interface {
	isShellRequest_Payload()
}

type ShellRequest_Start struct {
	Start *ShellStart `protobuf:"bytes,1,opt,name=start,proto3,oneof"`
}

type ShellRequest_Input struct {
	Input *ShellInput `protobuf:"bytes,2,opt,name=input,proto3,oneof"`
}

func (*ShellRequest_Start) isShellRequest_Payload() {}

func (*ShellRequest_Input) isShellRequest_Payload() {}

// ShellStart initiates a new shell session.
type ShellStart struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Args          []string               `protobuf:"bytes,1,rep,name=args,proto3" json:"args,omitempty"`
	Env           map[string]string      `protobuf:"bytes,2,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	WorkDir       string                 `protobuf:"bytes,3,opt,name=work_dir,json=workDir,proto3" json:"work_dir,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShellStart) Reset() {
	*x = ShellStart{}
	mi := &file_api_convoy_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShellStart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShellStart) ProtoMessage() {}

func (x *ShellStart) ProtoReflect() protoreflect.Message {
	mi := &file_api_convoy_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShellStart.ProtoReflect.Descriptor instead.
func (*ShellStart) Descriptor() ([]byte, []int) {
	return file_api_convoy_proto_rawDescGZIP(), []int{3}
}

func (x *ShellStart) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *ShellStart) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *ShellStart) GetWorkDir() string {
	if x != nil {
		return x.WorkDir
	}
	return ""
}

// ShellInput provides stdin data or closes the stream.
type ShellInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Eof           bool                   `protobuf:"varint,2,opt,name=eof,proto3" json:"eof,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShellInput) Reset() {
	*x = ShellInput{}
	mi := &file_api_convoy_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShellInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShellInput) ProtoMessage() {}

func (x *ShellInput) ProtoReflect() protoreflect.Message {
	mi := &file_api_convoy_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShellInput.ProtoReflect.Descriptor instead.
func (*ShellInput) Descriptor() ([]byte, []int) {
	return file_api_convoy_proto_rawDescGZIP(), []int{4}
}

func (x *ShellInput) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ShellInput) GetEof() bool {
	if x != nil {
		return x.Eof
	}
	return false
}

// ShellResponse streams output or exit events.
type ShellResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ShellResponse_Output
	//	*ShellResponse_Exit
	Payload       isShellResponse_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShellResponse) Reset() {
	*x = ShellResponse{}
	mi := &file_api_convoy_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShellResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShellResponse) ProtoMessage() {}

func (x *ShellResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_convoy_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShellResponse.ProtoReflect.Descriptor instead.
func (*ShellResponse) Descriptor() ([]byte, []int) {
	return file_api_convoy_proto_rawDescGZIP(), []int{5}
}

func (x *ShellResponse) GetPayload() isShellResponse_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ShellResponse) GetOutput() *ShellOutput {
	if x != nil {
		if x, ok := x.Payload.(*ShellResponse_Output); ok {
			return x.Output
		}
	}
	return nil
}

func (x *ShellResponse) GetExit() *ShellExit {
	if x != nil {
		if x, ok := x.Payload.(*ShellResponse_Exit); ok {
			return x.Exit
		}
	}
	return nil
}

type isShellResponse_Payload interface {
	isShellResponse_Payload()
}

type ShellResponse_Output struct {
	Output *ShellOutput `protobuf:"bytes,1,opt,name=output,proto3,oneof"`
}

type ShellResponse_Exit struct {
	Exit *ShellExit `protobuf:"bytes,2,opt,name=exit,proto3,oneof"`
}

func (*ShellResponse_Output) isShellResponse_Payload() {}

func (*ShellResponse_Exit) isShellResponse_Payload() {}

// ShellOutput identifies stdout vs stderr data chunks.
type ShellOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stream        ShellOutput_Stream     `protobuf:"varint,1,opt,name=stream,proto3,enum=convoy.ShellOutput_Stream" json:"stream,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShellOutput) Reset() {
	*x = ShellOutput{}
	mi := &file_api_convoy_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShellOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShellOutput) ProtoMessage() {}

func (x *ShellOutput) ProtoReflect() protoreflect.Message {
	mi := &file_api_convoy_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShellOutput.ProtoReflect.Descriptor instead.
func (*ShellOutput) Descriptor() ([]byte, []int) {
	return file_api_convoy_proto_rawDescGZIP(), []int{6}
}

func (x *ShellOutput) GetStream() ShellOutput_Stream {
	if x != nil {
		return x.Stream
	}
	return ShellOutput_STREAM_UNSPECIFIED
}

func (x *ShellOutput) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// ShellExit conveys the session result.
type ShellExit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExitCode      int32                  `protobuf:"varint,1,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShellExit) Reset() {
	*x = ShellExit{}
	mi := &file_api_convoy_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShellExit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShellExit) ProtoMessage() {}

func (x *ShellExit) ProtoReflect() protoreflect.Message {
	mi := &file_api_convoy_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShellExit.ProtoReflect.Descriptor instead.
func (*ShellExit) Descriptor() ([]byte, []int) {
	return file_api_convoy_proto_rawDescGZIP(), []int{7}
}

func (x *ShellExit) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *ShellExit) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// HealthRequest probes agent readiness/liveness.
type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Probe         string                 `protobuf:"bytes,1,opt,name=probe,proto3" json:"probe,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_api_convoy_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_convoy_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_api_convoy_proto_rawDescGZIP(), []int{8}
}

func (x *HealthRequest) GetProbe() string {
	if x != nil {
		return x.Probe
	}
	return ""
}

// HealthResponse reports agent status.
type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        HealthResponse_Status  `protobuf:"varint,1,opt,name=status,proto3,enum=convoy.HealthResponse_Status" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_api_convoy_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_convoy_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_api_convoy_proto_rawDescGZIP(), []int{9}
}

func (x *HealthResponse) GetStatus() HealthResponse_Status {
	if x != nil {
		return x.Status
	}
	return HealthResponse_STATUS_UNKNOWN
}

func (x *HealthResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// CopyRequest streams file data to/from the agent.
type CopyRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*CopyRequest_Start
	//	*CopyRequest_Chunk
	Payload       isCopyRequest_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CopyRequest) Reset() {
	*x = CopyRequest{}
	mi := &file_api_convoy_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CopyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CopyRequest) ProtoMessage() {}

func (x *CopyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_convoy_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CopyRequest.ProtoReflect.Descriptor instead.
func (*CopyRequest) Descriptor() ([]byte, []int) {
	return file_api_convoy_proto_rawDescGZIP(), []int{10}
}

func (x *CopyRequest) GetPayload() isCopyRequest_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *CopyRequest) GetStart() *CopyStart {
	if x != nil {
		if x, ok := x.Payload.(*CopyRequest_Start); ok {
			return x.Start
		}
	}
	return nil
}

func (x *CopyRequest) GetChunk() *CopyChunk {
	if x != nil {
		if x, ok := x.Payload.(*CopyRequest_Chunk); ok {
			return x.Chunk
		}
	}
	return nil
}

type isCopyRequest_Payload interface {
	isCopyRequest_Payload()
}

type CopyRequest_Start struct {
	Start *CopyStart `protobuf:"bytes,1,opt,name=start,proto3,oneof"`
}

type CopyRequest_Chunk struct {
	Chunk *CopyChunk `protobuf:"bytes,2,opt,name=chunk,proto3,oneof"`
}

func (*CopyRequest_Start) isCopyRequest_Payload() {}

func (*CopyRequest_Chunk) isCopyRequest_Payload() {}

// CopyStart initiates a copy operation.
type CopyStart struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Direction     CopyStart_Direction    `protobuf:"varint,1,opt,name=direction,proto3,enum=convoy.CopyStart_Direction" json:"direction,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`            // Destination path (TO_AGENT) or source path (FROM_AGENT)
	Overwrite     bool                   `protobuf:"varint,3,opt,name=overwrite,proto3" json:"overwrite,omitempty"` // Whether to overwrite existing files
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CopyStart) Reset() {
	*x = CopyStart{}
	mi := &file_api_convoy_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CopyStart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CopyStart) ProtoMessage() {}

func (x *CopyStart) ProtoReflect() protoreflect.Message {
	mi := &file_api_convoy_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CopyStart.ProtoReflect.Descriptor instead.
func (*CopyStart) Descriptor() ([]byte, []int) {
	return file_api_convoy_proto_rawDescGZIP(), []int{11}
}

func (x *CopyStart) GetDirection() CopyStart_Direction {
	if x != nil {
		return x.Direction
	}
	return CopyStart_DIRECTION_UNSPECIFIED
}

func (x *CopyStart) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *CopyStart) GetOverwrite() bool {
	if x != nil {
		return x.Overwrite
	}
	return false
}

// CopyChunk contains a chunk of tar data.
type CopyChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Eof           bool                   `protobuf:"varint,2,opt,name=eof,proto3" json:"eof,omitempty"` // Signals end of tar stream
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CopyChunk) Reset() {
	*x = CopyChunk{}
	mi := &file_api_convoy_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CopyChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CopyChunk) ProtoMessage() {}

func (x *CopyChunk) ProtoReflect() protoreflect.Message {
	mi := &file_api_convoy_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CopyChunk.ProtoReflect.Descriptor instead.
func (*CopyChunk) Descriptor() ([]byte, []int) {
	return file_api_convoy_proto_rawDescGZIP(), []int{12}
}

func (x *CopyChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *CopyChunk) GetEof() bool {
	if x != nil {
		return x.Eof
	}
	return false
}

// CopyResponse streams status and data back from the agent.
type CopyResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*CopyResponse_Progress
	//	*CopyResponse_Chunk
	//	*CopyResponse_Result
	Payload       isCopyResponse_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CopyResponse) Reset() {
	*x = CopyResponse{}
	mi := &file_api_convoy_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CopyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CopyResponse) ProtoMessage() {}

func (x *CopyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_convoy_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CopyResponse.ProtoReflect.Descriptor instead.
func (*CopyResponse) Descriptor() ([]byte, []int) {
	return file_api_convoy_proto_rawDescGZIP(), []int{13}
}

func (x *CopyResponse) GetPayload() isCopyResponse_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *CopyResponse) GetProgress() *CopyProgress {
	if x != nil {
		if x, ok := x.Payload.(*CopyResponse_Progress); ok {
			return x.Progress
		}
	}
	return nil
}

func (x *CopyResponse) GetChunk() *CopyChunk {
	if x != nil {
		if x, ok := x.Payload.(*CopyResponse_Chunk); ok {
			return x.Chunk
		}
	}
	return nil
}

func (x *CopyResponse) GetResult() *CopyResult {
	if x != nil {
		if x, ok := x.Payload.(*CopyResponse_Result); ok {
			return x.Result
		}
	}
	return nil
}

type isCopyResponse_Payload interface {
	isCopyResponse_Payload()
}

type CopyResponse_Progress struct {
	Progress *CopyProgress `protobuf:"bytes,1,opt,name=progress,proto3,oneof"`
}

type CopyResponse_Chunk struct {
	Chunk *CopyChunk `protobuf:"bytes,2,opt,name=chunk,proto3,oneof"`
}

type CopyResponse_Result struct {
	Result *CopyResult `protobuf:"bytes,3,opt,name=result,proto3,oneof"`
}

func (*CopyResponse_Progress) isCopyResponse_Payload() {}

func (*CopyResponse_Chunk) isCopyResponse_Payload() {}

func (*CopyResponse_Result) isCopyResponse_Payload() {}

// CopyProgress reports ongoing transfer status.
type CopyProgress struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	BytesTransferred int64                  `protobuf:"varint,1,opt,name=bytes_transferred,json=bytesTransferred,proto3" json:"bytes_transferred,omitempty"`
	CurrentFile      string                 `protobuf:"bytes,2,opt,name=current_file,json=currentFile,proto3" json:"current_file,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CopyProgress) Reset() {
	*x = CopyProgress{}
	mi := &file_api_convoy_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CopyProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CopyProgress) ProtoMessage() {}

func (x *CopyProgress) ProtoReflect() protoreflect.Message {
	mi := &file_api_convoy_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CopyProgress.ProtoReflect.Descriptor instead.
func (*CopyProgress) Descriptor() ([]byte, []int) {
	return file_api_convoy_proto_rawDescGZIP(), []int{14}
}

func (x *CopyProgress) GetBytesTransferred() int64 {
	if x != nil {
		return x.BytesTransferred
	}
	return 0
}

func (x *CopyProgress) GetCurrentFile() string {
	if x != nil {
		return x.CurrentFile
	}
	return ""
}

// CopyResult indicates the final outcome of the copy operation.
type CopyResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	TotalBytes    int64                  `protobuf:"varint,3,opt,name=total_bytes,json=totalBytes,proto3" json:"total_bytes,omitempty"`
	FileCount     int32                  `protobuf:"varint,4,opt,name=file_count,json=fileCount,proto3" json:"file_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CopyResult) Reset() {
	*x = CopyResult{}
	mi := &file_api_convoy_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CopyResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CopyResult) ProtoMessage() {}

func (x *CopyResult) ProtoReflect() protoreflect.Message {
	mi := &file_api_convoy_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CopyResult.ProtoReflect.Descriptor instead.
func (*CopyResult) Descriptor() ([]byte, []int) {
	return file_api_convoy_proto_rawDescGZIP(), []int{15}
}

func (x *CopyResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CopyResult) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CopyResult) GetTotalBytes() int64 {
	if x != nil {
		return x.TotalBytes
	}
	return 0
}

func (x *CopyResult) GetFileCount() int32 {
	if x != nil {
		return x.FileCount
	}
	return 0
}

var File_api_convoy_proto protoreflect.FileDescriptor

const file_api_convoy_proto_rawDesc = "" +
	"\n" +
	"\x10api/convoy.proto\x12\x06convoy\"\xd3\x01\n" +
	"\x0eCommandRequest\x12\x12\n" +
	"\x04args\x18\x01 \x03(\tR\x04args\x121\n" +
	"\x03env\x18\x02 \x03(\v2\x1f.convoy.CommandRequest.EnvEntryR\x03env\x12\x19\n" +
	"\bwork_dir\x18\x03 \x01(\tR\aworkDir\x12'\n" +
	"\x0ftimeout_seconds\x18\x04 \x01(\x05R\x0etimeoutSeconds\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x83\x01\n" +
	"\x0fCommandResponse\x12\x16\n" +
	"\x06stdout\x18\x01 \x01(\tR\x06stdout\x12\x16\n" +
	"\x06stderr\x18\x02 \x01(\tR\x06stderr\x12\x1b\n" +
	"\texit_code\x18\x03 \x01(\x05R\bexitCode\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\"q\n" +
	"\fShellRequest\x12*\n" +
	"\x05start\x18\x01 \x01(\v2\x12.convoy.ShellStartH\x00R\x05start\x12*\n" +
	"\x05input\x18\x02 \x01(\v2\x12.convoy.ShellInputH\x00R\x05inputB\t\n" +
	"\apayload\"\xa2\x01\n" +
	"\n" +
	"ShellStart\x12\x12\n" +
	"\x04args\x18\x01 \x03(\tR\x04args\x12-\n" +
	"\x03env\x18\x02 \x03(\v2\x1b.convoy.ShellStart.EnvEntryR\x03env\x12\x19\n" +
	"\bwork_dir\x18\x03 \x01(\tR\aworkDir\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"2\n" +
	"\n" +
	"ShellInput\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x10\n" +
	"\x03eof\x18\x02 \x01(\bR\x03eof\"r\n" +
	"\rShellResponse\x12-\n" +
	"\x06output\x18\x01 \x01(\v2\x13.convoy.ShellOutputH\x00R\x06output\x12'\n" +
	"\x04exit\x18\x02 \x01(\v2\x11.convoy.ShellExitH\x00R\x04exitB\t\n" +
	"\apayload\"\x8f\x01\n" +
	"\vShellOutput\x122\n" +
	"\x06stream\x18\x01 \x01(\x0e2\x1a.convoy.ShellOutput.StreamR\x06stream\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"8\n" +
	"\x06Stream\x12\x16\n" +
	"\x12STREAM_UNSPECIFIED\x10\x00\x12\n" +
	"\n" +
	"\x06STDOUT\x10\x01\x12\n" +
	"\n" +
	"\x06STDERR\x10\x02\"B\n" +
	"\tShellExit\x12\x1b\n" +
	"\texit_code\x18\x01 \x01(\x05R\bexitCode\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"%\n" +
	"\rHealthRequest\x12\x14\n" +
	"\x05probe\x18\x01 \x01(\tR\x05probe\"\xbe\x01\n" +
	"\x0eHealthResponse\x125\n" +
	"\x06status\x18\x01 \x01(\x0e2\x1d.convoy.HealthResponse.StatusR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"[\n" +
	"\x06Status\x12\x12\n" +
	"\x0eSTATUS_UNKNOWN\x10\x00\x12\x12\n" +
	"\x0eSTATUS_HEALTHY\x10\x01\x12\x13\n" +
	"\x0fSTATUS_DEGRADED\x10\x02\x12\x14\n" +
	"\x10STATUS_UNHEALTHY\x10\x03\"n\n" +
	"\vCopyRequest\x12)\n" +
	"\x05start\x18\x01 \x01(\v2\x11.convoy.CopyStartH\x00R\x05start\x12)\n" +
	"\x05chunk\x18\x02 \x01(\v2\x11.convoy.CopyChunkH\x00R\x05chunkB\t\n" +
	"\apayload\"\xbe\x01\n" +
	"\tCopyStart\x129\n" +
	"\tdirection\x18\x01 \x01(\x0e2\x1b.convoy.CopyStart.DirectionR\tdirection\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x1c\n" +
	"\toverwrite\x18\x03 \x01(\bR\toverwrite\"D\n" +
	"\tDirection\x12\x19\n" +
	"\x15DIRECTION_UNSPECIFIED\x10\x00\x12\f\n" +
	"\bTO_AGENT\x10\x01\x12\x0e\n" +
	"\n" +
	"FROM_AGENT\x10\x02\"1\n" +
	"\tCopyChunk\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x10\n" +
	"\x03eof\x18\x02 \x01(\bR\x03eof\"\xa6\x01\n" +
	"\fCopyResponse\x122\n" +
	"\bprogress\x18\x01 \x01(\v2\x14.convoy.CopyProgressH\x00R\bprogress\x12)\n" +
	"\x05chunk\x18\x02 \x01(\v2\x11.convoy.CopyChunkH\x00R\x05chunk\x12,\n" +
	"\x06result\x18\x03 \x01(\v2\x12.convoy.CopyResultH\x00R\x06resultB\t\n" +
	"\apayload\"^\n" +
	"\fCopyProgress\x12+\n" +
	"\x11bytes_transferred\x18\x01 \x01(\x03R\x10bytesTransferred\x12!\n" +
	"\fcurrent_file\x18\x02 \x01(\tR\vcurrentFile\"\x80\x01\n" +
	"\n" +
	"CopyResult\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1f\n" +
	"\vtotal_bytes\x18\x03 \x01(\x03R\n" +
	"totalBytes\x12\x1d\n" +
	"\n" +
	"file_count\x18\x04 \x01(\x05R\tfileCount2\x90\x02\n" +
	"\rConvoyService\x12C\n" +
	"\x0eExecuteCommand\x12\x16.convoy.CommandRequest\x1a\x17.convoy.CommandResponse\"\x00\x12A\n" +
	"\fExecuteShell\x12\x14.convoy.ShellRequest\x1a\x15.convoy.ShellResponse\"\x00(\x010\x01\x12>\n" +
	"\vCheckHealth\x12\x15.convoy.HealthRequest\x1a\x16.convoy.HealthResponse\"\x00\x127\n" +
	"\x04Copy\x12\x13.convoy.CopyRequest\x1a\x14.convoy.CopyResponse\"\x00(\x010\x01B\fZ\n" +
	"convoy/apib\x06proto3"

var (
	file_api_convoy_proto_rawDescOnce sync.Once
	file_api_convoy_proto_rawDescData []byte
)

func file_api_convoy_proto_rawDescGZIP() []byte {
	file_api_convoy_proto_rawDescOnce.Do(func() {
		file_api_convoy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_convoy_proto_rawDesc), len(file_api_convoy_proto_rawDesc)))
	})
	return file_api_convoy_proto_rawDescData
}

var file_api_convoy_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_api_convoy_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_api_convoy_proto_goTypes = []any{
	(ShellOutput_Stream)(0),    // 0: convoy.ShellOutput.Stream
	(HealthResponse_Status)(0), // 1: convoy.HealthResponse.Status
	(CopyStart_Direction)(0),   // 2: convoy.CopyStart.Direction
	(*CommandRequest)(nil),     // 3: convoy.CommandRequest
	(*CommandResponse)(nil),    // 4: convoy.CommandResponse
	(*ShellRequest)(nil),       // 5: convoy.ShellRequest
	(*ShellStart)(nil),         // 6: convoy.ShellStart
	(*ShellInput)(nil),         // 7: convoy.ShellInput
	(*ShellResponse)(nil),      // 8: convoy.ShellResponse
	(*ShellOutput)(nil),        // 9: convoy.ShellOutput
	(*ShellExit)(nil),          // 10: convoy.ShellExit
	(*HealthRequest)(nil),      // 11: convoy.HealthRequest
	(*HealthResponse)(nil),     // 12: convoy.HealthResponse
	(*CopyRequest)(nil),        // 13: convoy.CopyRequest
	(*CopyStart)(nil),          // 14: convoy.CopyStart
	(*CopyChunk)(nil),          // 15: convoy.CopyChunk
	(*CopyResponse)(nil),       // 16: convoy.CopyResponse
	(*CopyProgress)(nil),       // 17: convoy.CopyProgress
	(*CopyResult)(nil),         // 18: convoy.CopyResult
	nil,                        // 19: convoy.CommandRequest.EnvEntry
	nil,                        // 20: convoy.ShellStart.EnvEntry
}
var file_api_convoy_proto_depIdxs = []int32{
	19, // 0: convoy.CommandRequest.env:type_name -> convoy.CommandRequest.EnvEntry
	6,  // 1: convoy.ShellRequest.start:type_name -> convoy.ShellStart
	7,  // 2: convoy.ShellRequest.input:type_name -> convoy.ShellInput
	20, // 3: convoy.ShellStart.env:type_name -> convoy.ShellStart.EnvEntry
	9,  // 4: convoy.ShellResponse.output:type_name -> convoy.ShellOutput
	10, // 5: convoy.ShellResponse.exit:type_name -> convoy.ShellExit
	0,  // 6: convoy.ShellOutput.stream:type_name -> convoy.ShellOutput.Stream
	1,  // 7: convoy.HealthResponse.status:type_name -> convoy.HealthResponse.Status
	14, // 8: convoy.CopyRequest.start:type_name -> convoy.CopyStart
	15, // 9: convoy.CopyRequest.chunk:type_name -> convoy.CopyChunk
	2,  // 10: convoy.CopyStart.direction:type_name -> convoy.CopyStart.Direction
	17, // 11: convoy.CopyResponse.progress:type_name -> convoy.CopyProgress
	15, // 12: convoy.CopyResponse.chunk:type_name -> convoy.CopyChunk
	18, // 13: convoy.CopyResponse.result:type_name -> convoy.CopyResult
	3,  // 14: convoy.ConvoyService.ExecuteCommand:input_type -> convoy.CommandRequest
	5,  // 15: convoy.ConvoyService.ExecuteShell:input_type -> convoy.ShellRequest
	11, // 16: convoy.ConvoyService.CheckHealth:input_type -> convoy.HealthRequest
	13, // 17: convoy.ConvoyService.Copy:input_type -> convoy.CopyRequest
	4,  // 18: convoy.ConvoyService.ExecuteCommand:output_type -> convoy.CommandResponse
	8,  // 19: convoy.ConvoyService.ExecuteShell:output_type -> convoy.ShellResponse
	12, // 20: convoy.ConvoyService.CheckHealth:output_type -> convoy.HealthResponse
	16, // 21: convoy.ConvoyService.Copy:output_type -> convoy.CopyResponse
	18, // [18:22] is the sub-list for method output_type
	14, // [14:18] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_api_convoy_proto_init() }
func file_api_convoy_proto_init() {
	if File_api_convoy_proto != nil {
		return
	}
	file_api_convoy_proto_msgTypes[2].OneofWrappers = []any{
		(*ShellRequest_Start)(nil),
		(*ShellRequest_Input)(nil),
	}
	file_api_convoy_proto_msgTypes[5].OneofWrappers = []any{
		(*ShellResponse_Output)(nil),
		(*ShellResponse_Exit)(nil),
	}
	file_api_convoy_proto_msgTypes[10].OneofWrappers = []any{
		(*CopyRequest_Start)(nil),
		(*CopyRequest_Chunk)(nil),
	}
	file_api_convoy_proto_msgTypes[13].OneofWrappers = []any{
		(*CopyResponse_Progress)(nil),
		(*CopyResponse_Chunk)(nil),
		(*CopyResponse_Result)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_convoy_proto_rawDesc), len(file_api_convoy_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_convoy_proto_goTypes,
		DependencyIndexes: file_api_convoy_proto_depIdxs,
		EnumInfos:         file_api_convoy_proto_enumTypes,
		MessageInfos:      file_api_convoy_proto_msgTypes,
	}.Build()
	File_api_convoy_proto = out.File
	file_api_convoy_proto_goTypes = nil
	file_api_convoy_proto_depIdxs = nil
}
