// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: api/convoy.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ConvoyService_ExecuteCommand_FullMethodName = "/convoy.ConvoyService/ExecuteCommand"
	ConvoyService_ExecuteShell_FullMethodName   = "/convoy.ConvoyService/ExecuteShell"
	ConvoyService_CheckHealth_FullMethodName    = "/convoy.ConvoyService/CheckHealth"
	ConvoyService_Copy_FullMethodName           = "/convoy.ConvoyService/Copy"
)

// ConvoyServiceClient is the client API for ConvoyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ConvoyService exposes RPCs for executing commands and retrieving agent health.
type ConvoyServiceClient interface {
	ExecuteCommand(ctx context.Context, in *CommandRequest, opts ...grpc.CallOption) (*CommandResponse, error)
	ExecuteShell(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ShellRequest, ShellResponse], error)
	CheckHealth(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
	Copy(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[CopyRequest, CopyResponse], error)
}

type convoyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewConvoyServiceClient(cc grpc.ClientConnInterface) ConvoyServiceClient {
	return &convoyServiceClient{cc}
}

func (c *convoyServiceClient) ExecuteCommand(ctx context.Context, in *CommandRequest, opts ...grpc.CallOption) (*CommandResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommandResponse)
	err := c.cc.Invoke(ctx, ConvoyService_ExecuteCommand_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *convoyServiceClient) ExecuteShell(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ShellRequest, ShellResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ConvoyService_ServiceDesc.Streams[0], ConvoyService_ExecuteShell_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ShellRequest, ShellResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ConvoyService_ExecuteShellClient = grpc.BidiStreamingClient[ShellRequest, ShellResponse]

func (c *convoyServiceClient) CheckHealth(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, ConvoyService_CheckHealth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *convoyServiceClient) Copy(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[CopyRequest, CopyResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ConvoyService_ServiceDesc.Streams[1], ConvoyService_Copy_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[CopyRequest, CopyResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ConvoyService_CopyClient = grpc.BidiStreamingClient[CopyRequest, CopyResponse]

// ConvoyServiceServer is the server API for ConvoyService service.
// All implementations must embed UnimplementedConvoyServiceServer
// for forward compatibility.
//
// ConvoyService exposes RPCs for executing commands and retrieving agent health.
type ConvoyServiceServer interface {
	ExecuteCommand(context.Context, *CommandRequest) (*CommandResponse, error)
	ExecuteShell(grpc.BidiStreamingServer[ShellRequest, ShellResponse]) error
	CheckHealth(context.Context, *HealthRequest) (*HealthResponse, error)
	Copy(grpc.BidiStreamingServer[CopyRequest, CopyResponse]) error
	mustEmbedUnimplementedConvoyServiceServer()
}

// UnimplementedConvoyServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedConvoyServiceServer struct{}

func (UnimplementedConvoyServiceServer) ExecuteCommand(context.Context, *CommandRequest) (*CommandResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExecuteCommand not implemented")
}
func (UnimplementedConvoyServiceServer) ExecuteShell(grpc.BidiStreamingServer[ShellRequest, ShellResponse]) error {
	return status.Errorf(codes.Unimplemented, "method ExecuteShell not implemented")
}
func (UnimplementedConvoyServiceServer) CheckHealth(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckHealth not implemented")
}
func (UnimplementedConvoyServiceServer) Copy(grpc.BidiStreamingServer[CopyRequest, CopyResponse]) error {
	return status.Errorf(codes.Unimplemented, "method Copy not implemented")
}
func (UnimplementedConvoyServiceServer) mustEmbedUnimplementedConvoyServiceServer() {}
func (UnimplementedConvoyServiceServer) testEmbeddedByValue()                       {}

// UnsafeConvoyServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ConvoyServiceServer will
// result in compilation errors.
type UnsafeConvoyServiceServer interface {
	mustEmbedUnimplementedConvoyServiceServer()
}

func RegisterConvoyServiceServer(s grpc.ServiceRegistrar, srv ConvoyServiceServer) {
	// If the following call pancis, it indicates UnimplementedConvoyServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ConvoyService_ServiceDesc, srv)
}

func _ConvoyService_ExecuteCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConvoyServiceServer).ExecuteCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConvoyService_ExecuteCommand_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConvoyServiceServer).ExecuteCommand(ctx, req.(*CommandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConvoyService_ExecuteShell_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ConvoyServiceServer).ExecuteShell(&grpc.GenericServerStream[ShellRequest, ShellResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ConvoyService_ExecuteShellServer = grpc.BidiStreamingServer[ShellRequest, ShellResponse]

func _ConvoyService_CheckHealth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConvoyServiceServer).CheckHealth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConvoyService_CheckHealth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConvoyServiceServer).CheckHealth(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConvoyService_Copy_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ConvoyServiceServer).Copy(&grpc.GenericServerStream[CopyRequest, CopyResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ConvoyService_CopyServer = grpc.BidiStreamingServer[CopyRequest, CopyResponse]

// ConvoyService_ServiceDesc is the grpc.ServiceDesc for ConvoyService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ConvoyService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "convoy.ConvoyService",
	HandlerType: (*ConvoyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ExecuteCommand",
			Handler:    _ConvoyService_ExecuteCommand_Handler,
		},
		{
			MethodName: "CheckHealth",
			Handler:    _ConvoyService_CheckHealth_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ExecuteShell",
			Handler:       _ConvoyService_ExecuteShell_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "Copy",
			Handler:       _ConvoyService_Copy_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "api/convoy.proto",
}
